# Telecom customer churn Prediction - Data Preprocessing

In [1]:
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt

In [2]:
telecom_data = pd.read_excel("../data/Telco_customer_churn.xlsx")
telecom_data

,CustomerID,Count,Country,State,City,Zip Code,Lat Long,Latitude,Longitude,Gender,...,Contract,Paperless Billing,Payment Method,Monthly Charges,Total Charges,Churn Label,Churn Value,Churn Score,CLTV,Churn Reason
0,3668-QPYBK,1,United States,California,Los Angeles,90003,"33.964131, -118.272783",33.964131,-118.272783,Male,...,Month-to-month,Yes,Mailed check,53.85,108.15,Yes,1,86,3239,Competitor made better offer
1,9237-HQITU,1,United States,California,Los Angeles,90005,"34.059281, -118.30742",34.059281,-118.307420,Female,...,Month-to-month,Yes,Electronic check,70.70,151.65,Yes,1,67,2701,Moved
2,9305-CDSKC,1,United States,California,Los Angeles,90006,"34.048013, -118.293953",34.048013,-118.293953,Female,...,Month-to-month,Yes,Electronic check,99.65,820.5,Yes,1,86,5372,Moved
3,7892-POOKP,1,United States,California,Los Angeles,90010,"34.062125, -118.315709",34.062125,-118.315709,Female,...,Month-to-month,Yes,Electronic check,104.80,3046.05,Yes,1,84,5003,Moved
4,0280-XJGEX,1,United States,California,Los Angeles,90015,"34.039224, -118.266293",34.039224,-118.266293,Male,...,Month-to-month,Yes,Bank transfer (automatic),103.70,5036.3,Yes,1,89,5340,Competitor had better devices
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7038,2569-WGERO,1,United States,California,Landers,92285,"34.341737, -116.539416",34.341737,-116.539416,Female,...,Two year,Yes,Bank transfer (automatic),21.15,1419.4,No,0,45,5306,NaN
7039,6840-RESVB,1,United States,California,Adelanto,92301,"34.667815, -117.536183",34.667815,-117.536183,Male,...,One year,Yes,Mailed check,84.80,1990.5,No,0,59,2140,NaN
7040,2234-XADUH,1,United States,California,Amboy,92304,"34.559882, -115.637164",34.559882,-115.637164,Female,...,One year,Yes,Credit card (automatic),103.20,7362.9,No,0,71,5560,NaN
7041,4801-JZAZL,1,United States,California,Angelus Oaks,92305,"34.1678, -116.86433",34.167800,-116.864330,Female,...,Month-to-month,Yes,Electronic check,29.60,346.45,No,0,59,2793,NaN
7042,3186-AJIEK,1,United States,California,Apple Valley,92308,"34.424926, -117.184503",34.424926,-117.184503,Male,...,Two year,Yes,Bank transfer (automatic),105.65,6844.5,No,0,38,5097,NaN

In [3]:
telecom_data.columns

Index(['CustomerID', 'Count', 'Country', 'State', 'City', 'Zip Code',
       'Lat Long', 'Latitude', 'Longitude', 'Gender', 'Senior Citizen',
       'Partner', 'Dependents', 'Tenure Months', 'Phone Service',
       'Multiple Lines', 'Internet Service', 'Online Security',
       'Online Backup', 'Device Protection', 'Tech Support', 'Streaming TV',
       'Streaming Movies', 'Contract', 'Paperless Billing', 'Payment Method',
       'Monthly Charges', 'Total Charges', 'Churn Label', 'Churn Value',
       'Churn Score', 'CLTV', 'Churn Reason'],
      dtype='object')

In [4]:
telecom_data['Churn Reason'] = telecom_data['Churn Reason'].fillna("Existing User")

In [5]:
telecom_data['Total Charges'] = telecom_data['Total Charges'].replace(' ','0.0')
telecom_data = telecom_data.astype({'Tenure Months': 'float64','Total Charges': 'float64','CLTV':'float64'})

In [6]:
telecom_data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 7043 entries, 0 to 7042
Data columns (total 33 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   CustomerID         7043 non-null   object
 1   Count              7043 non-null   int64
 2   Country            7043 non-null   object
 3   State              7043 non-null   object
 4   City               7043 non-null   object
 5   Zip Code           7043 non-null   int64
 6   Lat Long           7043 non-null   object
 7   Latitude           7043 non-null   float64
 8   Longitude          7043 non-null   float64
 9   Gender             7043 non-null   object
 10  Senior Citizen     7043 non-null   object
 11  Partner            7043 non-null   object
 12  Dependents         7043 non-null   object
 13  Tenure Months      7043 non-null   float64
 14  Phone Service      7043 non-null   object
 15  Multiple Lines     7043 non-null   object
 16  Internet Service   7043 non-null   object
 17  Online Security    7043 non-null   object
 18  Online Backup      7043 non-null   object
 19  Device Protection  7043 non-null   object
 20  Tech Support       7043 non-null   object
 21  Streaming TV       7043 non-null   object
 22  Streaming Movies   7043 non-null   object
 23  Contract           7043 non-null   object
 24  Paperless Billing  7043 non-null   object
 25  Payment Method     7043 non-null   object
 26  Monthly Charges    7043 non-null   float64
 27  Total Charges      7043 non-null   float64
 28  Churn Label        7043 non-null   object
 29  Churn Value        7043 non-null   int64
 30  Churn Score        7043 non-null   int64
 31  CLTV               7043 non-null   float64
 32  Churn Reason       7043 non-null   object
dtypes: float64(6), int64(4), object(23)
memory usage: 1.8+ MB

## Encode Data

In [7]:
telecom_data['Partner'] = telecom_data.Partner.map({'Yes':1.0,'No':0.0})
telecom_data['Dependents'] = telecom_data.Dependents.map({'Yes':1.0,'No':0.0})
telecom_data['Senior Citizen'] = telecom_data['Senior Citizen'].map({'Yes':1.0,'No':0.0})
telecom_data['Phone Service'] = telecom_data['Phone Service'].map({'Yes':1.0,'No':0.0})
telecom_data['Multiple Lines'] = telecom_data['Multiple Lines'].map({'Yes':1.0,'No':0.0,'No phone service':0.0})

telecom_data['Online Security'] = telecom_data['Online Security'].map({'Yes':1.0,'No':0.0,'No internet service':0.0})
telecom_data['Online Backup'] = telecom_data['Online Backup'].map({'Yes':1.0,'No':0.0,'No internet service':0.0})
telecom_data['Device Protection'] = telecom_data['Device Protection'].map({'Yes':1.0,'No':0,'No internet service':0})
telecom_data['Tech Support'] = telecom_data['Tech Support'].map({'Yes':1.0,'No':0.0,'No internet service':0.0})
telecom_data['Streaming TV'] = telecom_data['Streaming TV'].map({'Yes':1.0,'No':0.0,'No internet service':0.0})
telecom_data['Streaming Movies'] = telecom_data['Streaming Movies'].map({'Yes':1.0,'No':0.0,'No internet service':0.0})

telecom_data['Paperless Billing'] = telecom_data['Paperless Billing'].map({'Yes':1.0,'No':0.0})

telecom_data

,CustomerID,Count,Country,State,City,Zip Code,Lat Long,Latitude,Longitude,Gender,...,Contract,Paperless Billing,Payment Method,Monthly Charges,Total Charges,Churn Label,Churn Value,Churn Score,CLTV,Churn Reason
0,3668-QPYBK,1,United States,California,Los Angeles,90003,"33.964131, -118.272783",33.964131,-118.272783,Male,...,Month-to-month,1.0,Mailed check,53.85,108.15,Yes,1,86,3239.0,Competitor made better offer
1,9237-HQITU,1,United States,California,Los Angeles,90005,"34.059281, -118.30742",34.059281,-118.307420,Female,...,Month-to-month,1.0,Electronic check,70.70,151.65,Yes,1,67,2701.0,Moved
2,9305-CDSKC,1,United States,California,Los Angeles,90006,"34.048013, -118.293953",34.048013,-118.293953,Female,...,Month-to-month,1.0,Electronic check,99.65,820.50,Yes,1,86,5372.0,Moved
3,7892-POOKP,1,United States,California,Los Angeles,90010,"34.062125, -118.315709",34.062125,-118.315709,Female,...,Month-to-month,1.0,Electronic check,104.80,3046.05,Yes,1,84,5003.0,Moved
4,0280-XJGEX,1,United States,California,Los Angeles,90015,"34.039224, -118.266293",34.039224,-118.266293,Male,...,Month-to-month,1.0,Bank transfer (automatic),103.70,5036.30,Yes,1,89,5340.0,Competitor had better devices
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7038,2569-WGERO,1,United States,California,Landers,92285,"34.341737, -116.539416",34.341737,-116.539416,Female,...,Two year,1.0,Bank transfer (automatic),21.15,1419.40,No,0,45,5306.0,Existing User
7039,6840-RESVB,1,United States,California,Adelanto,92301,"34.667815, -117.536183",34.667815,-117.536183,Male,...,One year,1.0,Mailed check,84.80,1990.50,No,0,59,2140.0,Existing User
7040,2234-XADUH,1,United States,California,Amboy,92304,"34.559882, -115.637164",34.559882,-115.637164,Female,...,One year,1.0,Credit card (automatic),103.20,7362.90,No,0,71,5560.0,Existing User
7041,4801-JZAZL,1,United States,California,Angelus Oaks,92305,"34.1678, -116.86433",34.167800,-116.864330,Female,...,Month-to-month,1.0,Electronic check,29.60,346.45,No,0,59,2793.0,Existing User
7042,3186-AJIEK,1,United States,California,Apple Valley,92308,"34.424926, -117.184503",34.424926,-117.184503,Male,...,Two year,1.0,Bank transfer (automatic),105.65,6844.50,No,0,38,5097.0,Existing User

In [8]:
def encode_internet_service(row):
    if row['Internet Service'] == 'DSL':
        row['Internet Service - DSL'] = 1.0
        row['Internet Service - Fiber optic'] = 0.0
    elif row['Internet Service'] == 'Fiber optic':
        row['Internet Service - DSL'] = 0.0
        row['Internet Service - Fiber optic'] = 1.0
    else:
        row['Internet Service - DSL'] = 0.0
        row['Internet Service - Fiber optic'] = 0.0
    return row

telecom_data = telecom_data.apply(encode_internet_service, axis=1)
telecom_data

,CustomerID,Count,Country,State,City,Zip Code,Lat Long,Latitude,Longitude,Gender,...,Payment Method,Monthly Charges,Total Charges,Churn Label,Churn Value,Churn Score,CLTV,Churn Reason,Internet Service - DSL,Internet Service - Fiber optic
0,3668-QPYBK,1,United States,California,Los Angeles,90003,"33.964131, -118.272783",33.964131,-118.272783,Male,...,Mailed check,53.85,108.15,Yes,1,86,3239.0,Competitor made better offer,1.0,0.0
1,9237-HQITU,1,United States,California,Los Angeles,90005,"34.059281, -118.30742",34.059281,-118.307420,Female,...,Electronic check,70.70,151.65,Yes,1,67,2701.0,Moved,0.0,1.0
2,9305-CDSKC,1,United States,California,Los Angeles,90006,"34.048013, -118.293953",34.048013,-118.293953,Female,...,Electronic check,99.65,820.50,Yes,1,86,5372.0,Moved,0.0,1.0
3,7892-POOKP,1,United States,California,Los Angeles,90010,"34.062125, -118.315709",34.062125,-118.315709,Female,...,Electronic check,104.80,3046.05,Yes,1,84,5003.0,Moved,0.0,1.0
4,0280-XJGEX,1,United States,California,Los Angeles,90015,"34.039224, -118.266293",34.039224,-118.266293,Male,...,Bank transfer (automatic),103.70,5036.30,Yes,1,89,5340.0,Competitor had better devices,0.0,1.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7038,2569-WGERO,1,United States,California,Landers,92285,"34.341737, -116.539416",34.341737,-116.539416,Female,...,Bank transfer (automatic),21.15,1419.40,No,0,45,5306.0,Existing User,0.0,0.0
7039,6840-RESVB,1,United States,California,Adelanto,92301,"34.667815, -117.536183",34.667815,-117.536183,Male,...,Mailed check,84.80,1990.50,No,0,59,2140.0,Existing User,1.0,0.0
7040,2234-XADUH,1,United States,California,Amboy,92304,"34.559882, -115.637164",34.559882,-115.637164,Female,...,Credit card (automatic),103.20,7362.90,No,0,71,5560.0,Existing User,0.0,1.0
7041,4801-JZAZL,1,United States,California,Angelus Oaks,92305,"34.1678, -116.86433",34.167800,-116.864330,Female,...,Electronic check,29.60,346.45,No,0,59,2793.0,Existing User,1.0,0.0
7042,3186-AJIEK,1,United States,California,Apple Valley,92308,"34.424926, -117.184503",34.424926,-117.184503,Male,...,Bank transfer (automatic),105.65,6844.50,No,0,38,5097.0,Existing User,0.0,1.0

In [9]:
def encode_payment_method(row):
    if row['Payment Method'] == 'Mailed check':
        row['Payment Method - Mailed check'] = 1.0
        row['Payment Method - Electronic check'] = 0.0
        row['Payment Method - Bank transfer (automatic)'] = 0.0
        row['Payment Method - Credit card (automatic)'] = 0.0
    elif row['Payment Method'] == 'Electronic check':
        row['Payment Method - Mailed check'] = 0.0
        row['Payment Method - Electronic check'] = 1.0
        row['Payment Method - Bank transfer (automatic)'] = 0.0
        row['Payment Method - Credit card (automatic)'] = 0.0
    elif row['Payment Method'] == 'Bank transfer (automatic)':
        row['Payment Method - Mailed check'] = 0.0
        row['Payment Method - Electronic check'] = 0.0
        row['Payment Method - Bank transfer (automatic)'] = 1.0
        row['Payment Method - Credit card (automatic)'] = 0.0
    elif row['Payment Method'] == 'Credit card (automatic)':
        row['Payment Method - Mailed check'] = 0.0
        row['Payment Method - Electronic check'] = 0.0
        row['Payment Method - Bank transfer (automatic)'] = 0.0
        row['Payment Method - Credit card (automatic)'] = 1.0
    return row

telecom_data = telecom_data.apply(encode_payment_method, axis=1)
telecom_data

,CustomerID,Count,Country,State,City,Zip Code,Lat Long,Latitude,Longitude,Gender,...,Churn Value,Churn Score,CLTV,Churn Reason,Internet Service - DSL,Internet Service - Fiber optic,Payment Method - Mailed check,Payment Method - Electronic check,Payment Method - Bank transfer (automatic),Payment Method - Credit card (automatic)
0,3668-QPYBK,1,United States,California,Los Angeles,90003,"33.964131, -118.272783",33.964131,-118.272783,Male,...,1,86,3239.0,Competitor made better offer,1.0,0.0,1.0,0.0,0.0,0.0
1,9237-HQITU,1,United States,California,Los Angeles,90005,"34.059281, -118.30742",34.059281,-118.307420,Female,...,1,67,2701.0,Moved,0.0,1.0,0.0,1.0,0.0,0.0
2,9305-CDSKC,1,United States,California,Los Angeles,90006,"34.048013, -118.293953",34.048013,-118.293953,Female,...,1,86,5372.0,Moved,0.0,1.0,0.0,1.0,0.0,0.0
3,7892-POOKP,1,United States,California,Los Angeles,90010,"34.062125, -118.315709",34.062125,-118.315709,Female,...,1,84,5003.0,Moved,0.0,1.0,0.0,1.0,0.0,0.0
4,0280-XJGEX,1,United States,California,Los Angeles,90015,"34.039224, -118.266293",34.039224,-118.266293,Male,...,1,89,5340.0,Competitor had better devices,0.0,1.0,0.0,0.0,1.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7038,2569-WGERO,1,United States,California,Landers,92285,"34.341737, -116.539416",34.341737,-116.539416,Female,...,0,45,5306.0,Existing User,0.0,0.0,0.0,0.0,1.0,0.0
7039,6840-RESVB,1,United States,California,Adelanto,92301,"34.667815, -117.536183",34.667815,-117.536183,Male,...,0,59,2140.0,Existing User,1.0,0.0,1.0,0.0,0.0,0.0
7040,2234-XADUH,1,United States,California,Amboy,92304,"34.559882, -115.637164",34.559882,-115.637164,Female,...,0,71,5560.0,Existing User,0.0,1.0,0.0,0.0,0.0,1.0
7041,4801-JZAZL,1,United States,California,Angelus Oaks,92305,"34.1678, -116.86433",34.167800,-116.864330,Female,...,0,59,2793.0,Existing User,1.0,0.0,0.0,1.0,0.0,0.0
7042,3186-AJIEK,1,United States,California,Apple Valley,92308,"34.424926, -117.184503",34.424926,-117.184503,Male,...,0,38,5097.0,Existing User,0.0,1.0,0.0,0.0,1.0,0.0

In [10]:
def encode_contract(row):
    if row['Contract'] == 'One year':
        row['Contract - One year'] = 1.0
        row['Contract - Two year'] = 0.0
        row['Contract - Month-to-month'] = 0.0
    elif row['Contract'] == 'Two year':
        row['Contract - One year'] = 0.0
        row['Contract - Two year'] = 1.0
        row['Contract - Month-to-month'] = 0.0
    elif row['Contract'] == 'Month-to-month':
        row['Contract - One year'] = 0.0
        row['Contract - Two year'] = 0.0
        row['Contract - Month-to-month'] = 1.0
    return row

telecom_data = telecom_data.apply(encode_contract, axis=1)
telecom_data

,CustomerID,Count,Country,State,City,Zip Code,Lat Long,Latitude,Longitude,Gender,...,Churn Reason,Internet Service - DSL,Internet Service - Fiber optic,Payment Method - Mailed check,Payment Method - Electronic check,Payment Method - Bank transfer (automatic),Payment Method - Credit card (automatic),Contract - One year,Contract - Two year,Contract - Month-to-month
0,3668-QPYBK,1,United States,California,Los Angeles,90003,"33.964131, -118.272783",33.964131,-118.272783,Male,...,Competitor made better offer,1.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,1.0
1,9237-HQITU,1,United States,California,Los Angeles,90005,"34.059281, -118.30742",34.059281,-118.307420,Female,...,Moved,0.0,1.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0
2,9305-CDSKC,1,United States,California,Los Angeles,90006,"34.048013, -118.293953",34.048013,-118.293953,Female,...,Moved,0.0,1.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0
3,7892-POOKP,1,United States,California,Los Angeles,90010,"34.062125, -118.315709",34.062125,-118.315709,Female,...,Moved,0.0,1.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0
4,0280-XJGEX,1,United States,California,Los Angeles,90015,"34.039224, -118.266293",34.039224,-118.266293,Male,...,Competitor had better devices,0.0,1.0,0.0,0.0,1.0,0.0,0.0,0.0,1.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7038,2569-WGERO,1,United States,California,Landers,92285,"34.341737, -116.539416",34.341737,-116.539416,Female,...,Existing User,0.0,0.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0
7039,6840-RESVB,1,United States,California,Adelanto,92301,"34.667815, -117.536183",34.667815,-117.536183,Male,...,Existing User,1.0,0.0,1.0,0.0,0.0,0.0,1.0,0.0,0.0
7040,2234-XADUH,1,United States,California,Amboy,92304,"34.559882, -115.637164",34.559882,-115.637164,Female,...,Existing User,0.0,1.0,0.0,0.0,0.0,1.0,1.0,0.0,0.0
7041,4801-JZAZL,1,United States,California,Angelus Oaks,92305,"34.1678, -116.86433",34.167800,-116.864330,Female,...,Existing User,1.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0
7042,3186-AJIEK,1,United States,California,Apple Valley,92308,"34.424926, -117.184503",34.424926,-117.184503,Male,...,Existing User,0.0,1.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0

In [11]:
def encode_gender(row):
    if row['Gender'] == 'Female':
        row['Female'] = 1.0
        row['Male'] = 0.0
    else:
        row['Female'] = 0.0
        row['Male'] = 1.0
    return row

telecom_data = telecom_data.apply(encode_gender, axis=1)
telecom_data

,CustomerID,Count,Country,State,City,Zip Code,Lat Long,Latitude,Longitude,Gender,...,Internet Service - Fiber optic,Payment Method - Mailed check,Payment Method - Electronic check,Payment Method - Bank transfer (automatic),Payment Method - Credit card (automatic),Contract - One year,Contract - Two year,Contract - Month-to-month,Female,Male
0,3668-QPYBK,1,United States,California,Los Angeles,90003,"33.964131, -118.272783",33.964131,-118.272783,Male,...,0.0,1.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,1.0
1,9237-HQITU,1,United States,California,Los Angeles,90005,"34.059281, -118.30742",34.059281,-118.307420,Female,...,1.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0,1.0,0.0
2,9305-CDSKC,1,United States,California,Los Angeles,90006,"34.048013, -118.293953",34.048013,-118.293953,Female,...,1.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0,1.0,0.0
3,7892-POOKP,1,United States,California,Los Angeles,90010,"34.062125, -118.315709",34.062125,-118.315709,Female,...,1.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0,1.0,0.0
4,0280-XJGEX,1,United States,California,Los Angeles,90015,"34.039224, -118.266293",34.039224,-118.266293,Male,...,1.0,0.0,0.0,1.0,0.0,0.0,0.0,1.0,0.0,1.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7038,2569-WGERO,1,United States,California,Landers,92285,"34.341737, -116.539416",34.341737,-116.539416,Female,...,0.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0,1.0,0.0
7039,6840-RESVB,1,United States,California,Adelanto,92301,"34.667815, -117.536183",34.667815,-117.536183,Male,...,0.0,1.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,1.0
7040,2234-XADUH,1,United States,California,Amboy,92304,"34.559882, -115.637164",34.559882,-115.637164,Female,...,1.0,0.0,0.0,0.0,1.0,1.0,0.0,0.0,1.0,0.0
7041,4801-JZAZL,1,United States,California,Angelus Oaks,92305,"34.1678, -116.86433",34.167800,-116.864330,Female,...,0.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0,1.0,0.0
7042,3186-AJIEK,1,United States,California,Apple Valley,92308,"34.424926, -117.184503",34.424926,-117.184503,Male,...,1.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0,0.0,1.0

In [12]:
telecom_data.columns

Index(['CustomerID', 'Count', 'Country', 'State', 'City', 'Zip Code',
       'Lat Long', 'Latitude', 'Longitude', 'Gender', 'Senior Citizen',
       'Partner', 'Dependents', 'Tenure Months', 'Phone Service',
       'Multiple Lines', 'Internet Service', 'Online Security',
       'Online Backup', 'Device Protection', 'Tech Support', 'Streaming TV',
       'Streaming Movies', 'Contract', 'Paperless Billing', 'Payment Method',
       'Monthly Charges', 'Total Charges', 'Churn Label', 'Churn Value',
       'Churn Score', 'CLTV', 'Churn Reason', 'Internet Service - DSL',
       'Internet Service - Fiber optic', 'Payment Method - Mailed check',
       'Payment Method - Electronic check',
       'Payment Method - Bank transfer (automatic)',
       'Payment Method - Credit card (automatic)', 'Contract - One year',
       'Contract - Two year', 'Contract - Month-to-month', 'Female', 'Male'],
      dtype='object')

In [13]:
selected_columns = ['Female','Male', 'Senior Citizen',
       'Partner', 'Dependents', 'Tenure Months', 'Phone Service',
       'Multiple Lines', 'Internet Service - DSL','Internet Service - Fiber optic', 'Online Security',
       'Online Backup', 'Device Protection', 'Tech Support', 'Streaming TV',
       'Streaming Movies', 'Contract - One year',
       'Contract - Two year', 'Contract - Month-to-month', 'Paperless Billing', 'Payment Method - Mailed check',
       'Payment Method - Electronic check',
       'Payment Method - Bank transfer (automatic)',
       'Payment Method - Credit card (automatic)',
       'Monthly Charges', 'Total Charges', 'Churn Value', 'CLTV']
telecom_data = telecom_data[selected_columns]

In [14]:
telecom_data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 7043 entries, 0 to 7042
Data columns (total 28 columns):
 #   Column                                      Non-Null Count  Dtype
---  ------                                      --------------  -----
 0   Female                                      7043 non-null   float64
 1   Male                                        7043 non-null   float64
 2   Senior Citizen                              7043 non-null   float64
 3   Partner                                     7043 non-null   float64
 4   Dependents                                  7043 non-null   float64
 5   Tenure Months                               7043 non-null   float64
 6   Phone Service                               7043 non-null   float64
 7   Multiple Lines                              7043 non-null   float64
 8   Internet Service - DSL                      7043 non-null   float64
 9   Internet Service - Fiber optic              7043 non-null   float64
 10  Online Security                             7043 non-null   float64
 11  Online Backup                               7043 non-null   float64
 12  Device Protection                           7043 non-null   float64
 13  Tech Support                                7043 non-null   float64
 14  Streaming TV                                7043 non-null   float64
 15  Streaming Movies                            7043 non-null   float64
 16  Contract - One year                         7043 non-null   float64
 17  Contract - Two year                         7043 non-null   float64
 18  Contract - Month-to-month                   7043 non-null   float64
 19  Paperless Billing                           7043 non-null   float64
 20  Payment Method - Mailed check               7043 non-null   float64
 21  Payment Method - Electronic check           7043 non-null   float64
 22  Payment Method - Bank transfer (automatic)  7043 non-null   float64
 23  Payment Method - Credit card (automatic)    7043 non-null   float64
 24  Monthly Charges                             7043 non-null   float64
 25  Total Charges                               7043 non-null   float64
 26  Churn Value                                 7043 non-null   int64
 27  CLTV                                        7043 non-null   float64
dtypes: float64(27), int64(1)
memory usage: 1.5 MB

In [15]:
telecom_data

,Female,Male,Senior Citizen,Partner,Dependents,Tenure Months,Phone Service,Multiple Lines,Internet Service - DSL,Internet Service - Fiber optic,...,Contract - Month-to-month,Paperless Billing,Payment Method - Mailed check,Payment Method - Electronic check,Payment Method - Bank transfer (automatic),Payment Method - Credit card (automatic),Monthly Charges,Total Charges,Churn Value,CLTV
0,0.0,1.0,0.0,0.0,0.0,2.0,1.0,0.0,1.0,0.0,...,1.0,1.0,1.0,0.0,0.0,0.0,53.85,108.15,1,3239.0
1,1.0,0.0,0.0,0.0,1.0,2.0,1.0,0.0,0.0,1.0,...,1.0,1.0,0.0,1.0,0.0,0.0,70.70,151.65,1,2701.0
2,1.0,0.0,0.0,0.0,1.0,8.0,1.0,1.0,0.0,1.0,...,1.0,1.0,0.0,1.0,0.0,0.0,99.65,820.50,1,5372.0
3,1.0,0.0,0.0,1.0,1.0,28.0,1.0,1.0,0.0,1.0,...,1.0,1.0,0.0,1.0,0.0,0.0,104.80,3046.05,1,5003.0
4,0.0,1.0,0.0,0.0,1.0,49.0,1.0,1.0,0.0,1.0,...,1.0,1.0,0.0,0.0,1.0,0.0,103.70,5036.30,1,5340.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7038,1.0,0.0,0.0,0.0,0.0,72.0,1.0,0.0,0.0,0.0,...,0.0,1.0,0.0,0.0,1.0,0.0,21.15,1419.40,0,5306.0
7039,0.0,1.0,0.0,1.0,1.0,24.0,1.0,1.0,1.0,0.0,...,0.0,1.0,1.0,0.0,0.0,0.0,84.80,1990.50,0,2140.0
7040,1.0,0.0,0.0,1.0,1.0,72.0,1.0,1.0,0.0,1.0,...,0.0,1.0,0.0,0.0,0.0,1.0,103.20,7362.90,0,5560.0
7041,1.0,0.0,0.0,1.0,1.0,11.0,0.0,0.0,1.0,0.0,...,1.0,1.0,0.0,1.0,0.0,0.0,29.60,346.45,0,2793.0
7042,0.0,1.0,0.0,0.0,0.0,66.0,1.0,0.0,0.0,1.0,...,0.0,1.0,0.0,0.0,1.0,0.0,105.65,6844.50,0,5097.0